#!/bin/bash
# This script require root access, it should be run via sudo

# Exit if ip address not supplied.  
[[ $1 ~= '\A\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z' ]] && echo "Command requires a valid ip address be specified [sudo pifi-ip 192.168.1.77" && exit 1

# delete existing ip specification, if any
sed -i "s/ip=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z//" /boot/cmdline.txt

# add new ip specifications
echo "ip=$1" >> /boot/cmdline.txt
