#!/bin/bash
# This script require root access, it should be run via sudo

# exit if on/off command not provided as argument
[[ $1 != 'on' || $1 != 'off' ]] && echo "Command requires on/off specification [sudo pifi-wifi on | sudo pifi-wifi off]" && exit 1

iwconfig wlan0 txpower $1
